### ISSUE TITLE
Commits in VSCode

### ISSUE THREAD

**Issue by alexllao** [di-sukharev/opencommit#1]
Would it be possible to integrate it into VSCode? In this way, when making the commits from there, we would not have to go through the terminal.

**Comment by di-sukharev** [comment]
It's kinda possible :)

just run `oc hook set` and you can then click "Enter" key in the empty Source Control input and VSCode will open a file for editing the commit. 

If VSCode doesn't open the commit editing window — you should probably turn on this setting:
<img width="1060" alt="Screenshot 2023-03-10 at 17 49 24" src="https://user-images.githubusercontent.com/57486732/224283847-93bcc767-5a9a-4500-85ec-570d3680a1dd.png">

**Comment by di-sukharev** [comment]
hehe, this look like an issue, do you want to make a PR?

**Comment by di-sukharev** [comment]
looks like an issue, shouldn't be conflicting with your hook. Anyway, do you want to research locally and make a PR?

**Comment by alexllao** [comment]
ufff i'm a newbye.

**Comment by alexllao** [comment]
I've this in my package.json

"husky": {
        "hooks": {
            "pre-commit": "lint-staged"
        }
    },
    "lint-staged": {
        "**/*.{ts,tsx,md,js,jsx,json}": [
            "prettier --write \"**/*.{ts,tsx,md,js,jsx,json}\""
        ]
    },

**Comment by alexllao** [comment]
It would be interesting if by committing within VSCode, with the "SoureControl" plugin, and not passing any message to it, it would already do everything automatically.

Is it possible to define it in commit language?

![Sin-título-1](https://user-images.githubusercontent.com/8004573/224290001-0ee77b6b-c05b-4881-bd66-c95141c8c962.png)

**Comment by alexllao** [comment]
I think that issue may come from Windows.

**Comment by di-sukharev** [comment]
will investigate, thanks bro

**Comment by lennartle** [comment]
is there any reason to make it a CLI tool? this is should be a vscode extension, openai key should be configured in vscode settings. it should not include any functionality besides comparing a diff of already staged files, it should have an icon button that generates a text in the commit message window which I can edit. 

![image](https://user-images.githubusercontent.com/45395412/224421820-036fa00b-7d6e-4a33-8031-0f131f2ed07e.png)

I don't want to install anything globally, and while configuring an API key I've got an execution policy error on windows.

**Comment by di-sukharev** [comment]
> Besides CLI there is should be a vscode extension, openai key should be configured in vscode settings. also, it should not include any functionality besides comparing a diff of already staged files, it should have an icon button that suggests a text in the commit message window that I can edit.
> 
> ![image](https://user-images.githubusercontent.com/45395412/224421820-036fa00b-7d6e-4a33-8031-0f131f2ed07e.png)
> 
> I don't want to install anything globally, and while configuring an API key I've got an execution policy error on windows.

Could you provide error message pls

**Comment by BenjaminHoegh** [comment]
any ways to auto `oc hook set`?

**Comment by di-sukharev** [comment]
> any ways to auto `oc hook set`?

i don't think it's a good idea, people could have their own hooks set, config `true/false` is ok here

**Comment by mze9412** [comment]
I have a similar issue with VSCode remote development. I run oc on the remote machine from the integrated terminal in VSCode and don't get a suggested message in VSCode. The hook is set viia `oc hook set`

**Comment by di-sukharev** [comment]
> I have a similar issue with VSCode remote development. I run oc on the remote machine from the integrated terminal in VSCode and don't get a suggested message in VSCode. The hook is set viia `oc hook set`

any error messages? how does the issue look? :)

**Comment by mze9412** [comment]
When I run `oc` I get a commit message generated but cannot edit or see it inside VSCode. No error messages.

**Comment by lennartle** [comment]
> When I run `oc` I get a commit message generated but cannot edit or see it inside VSCode. No error messages.

try chadCommit extension

**Comment by di-sukharev** [comment]
@mze9412 you should enable setting in VSCode  https://github.com/di-sukharev/opencommit/issues/1#issuecomment-1463546118

**Comment by robertoandrade** [comment]
Although I very much like the prompt and results from opencommit, I'd also like the ease of the GUI shortcut like some others have implemented:
- https://github.com/pwwang/vscode-gptcommit
- https://github.com/dmytrobaida/GPTCommitVSCode

Perhaps it could be as easy as forking one of those repos and stripping `gptcommit` out of it and swapping it by `opencommit`?
