### ISSUE TITLE
Payment description in README

### ISSUE THREAD

**Issue by Christopher-Hayes** [di-sukharev/opencommit#106]
from the README.md:

> You pay for your own requests to OpenAI API. OpenCommit uses ChatGPT official model, that is ~10x times cheaper than GPT-3 and ~6x times cheaper than GPT-4.

Is this correct? I'm a little confused by the wording. How can it be 10x cheaper than GPT-3, but only 6x cheaper than GPT-4?

From my calculations, GPT-4 is approximately 30x more expensive than GPT-3.5-turbo (completions specifically). Is OpenCommit using the davinci-003 prompt complete, or something else? Those 10x cheaper and 6x cheaper values seem off.

Btw, love the idea. I already love gitmoji, so happy opencommit supports it and I can automate it with ai.

**Comment by di-sukharev** [comment]
hehe, thats the wording from openAI guys, how did you do calculations so you get 30x?

**Comment by di-sukharev** [comment]
fixed the wording, thanks brother
