### ISSUE TITLE
Compatibility with delta?

### ISSUE THREAD

**Issue by thisismygitrepo** [di-sukharev/opencommit#109]
One of the most famous convivence tools is `delta`  `https://github.com/dandavison/delta`

It hacks `git diff` functionality to produce fancy comparison.

I think `opencommit` is being thrown up by the format of the output which is like vertical split of screen where left and right show old version and new version.

I concluded this upon close inspection of commit messages. Concretely, it goes about describing old code as if it is a new modification which is not true.

I'm not sure if there is an easy fix for this.

**Comment by di-sukharev** [comment]
hi hi 

I havent seen `oc` describing old code as if its new. what do you suggest anyway?

**Comment by thisismygitrepo** [comment]
I'm close this because I was telling a lie as it turns out.
