### ISSUE TITLE
[Feature]: Rename the alias `oc` to avoid conflicting with Openshift OC client.

### ISSUE THREAD

**Issue by flagsibh** [di-sukharev/opencommit#118]
### Description

This app also creates an alias named `oc`. If you happen to use the Openshift Client, also named `oc`, you'll get a naming conflict and the new tool will override the OCP client.

### Suggested Solution

Pkease, rename the alias to something like `oco`, `ocom`, `ocommits`...

**Comment by EsmerlinJM** [comment]
+1 Will be cool if you can select option before install.

**Comment by di-sukharev** [comment]
thanks for the issue, you can now use `oco`, update `npm i -g opencommit@latest`, use `sudo` if needed
