### ISSUE TITLE
Error: Unsupported config key: sk-iQixtQCJ61k8jbqsENVnT3Bl****************

### ISSUE THREAD

**Issue by paivaric** [di-sukharev/opencommit#12]
Error running config api key command:

opencommit config set sk-iQixtQCJ61k8jbqsENVnT3Bl****************

┌  opencommit — config
│
└  ✖ Error: Unsupported config key: sk-iQixtQCJ61k8jbqsENVnT3Bl****************

**Comment by di-sukharev** [comment]
@paivaric but make sure you change ************* with real numbers. You basically need to get API key from openAI and paste it instead of `<your_api_key>` in `opencommit config set OPENAI_API_KEY=<your_api_key>`

**Comment by di-sukharev** [comment]
are we done here?
