### ISSUE TITLE
[Bug]:   ✖ Error: Request failed with status code 429

### ISSUE THREAD

**Issue by DorianMairy** [di-sukharev/opencommit#141]
### Opencommit Version

2.0.0

### Node Version

16.20.0

### NPM Version

9.6.5

### What OS are you seeing the problem on?

Windows

### What happened?

A bug happened!

i have the error : 

◓  Generating the commit message   
│
└  ✖ Error: Request failed with status code 429

when the oc generate a message

### Expected Behavior

its work ^^'

### Current Behavior

 ✖ Error: Request failed with status code 429

**Comment by miggi92** [comment]
OpenAI Error Code:
`Error Code 429 - Rate limit reached for requests`

https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests 

Same issues:
#7 
#66 ( still open )

**Comment by codeagencybe** [comment]
I have this problem too and I'm the only user using the key. 
And i'm not exagerating with the usage either. The error 429 comes very random adhoc. 
Sometimes I didn't commit anything for 2 hours and I still hit error 429. I try again immediately after and it works. 
If it would be rate limiting, then it doesn't make sense that a second subtry immediately later would let it pass. 

I think it's more likely an overload from their servers which is also handled on same error code as documented here: 
https://help.openai.com/en/articles/6891834-error-code-429-the-engine-is-currently-overloaded-please-try-again-later

**Comment by MendyLanda** [comment]
I too encountered the same error, I was on the free trial.
it was solved by adding a credit card to OpenAI and generating a new secret after. 
As @codeagencybe noted, this error is solely due to openai api issues.
