### ISSUE TITLE
[Feature]: Installation via HomeBrew

### ISSUE THREAD

**Issue by Moulick** [di-sukharev/opencommit#143]
### Description

It would be helpful to make `opencommit` installable via Homebrew. Many people prefer installation via brew (myself included). This would increase the reach of `opencommit`, particularly with people who don't deal with NPM, JS, etc.

### Suggested Solution

`OpenCommit` is installable via HomeBrew. I can make the PR to Homebrew to add this project.

**Comment by di-sukharev** [comment]
please make the PR

**Comment by Moulick** [comment]
Here we go: https://github.com/Homebrew/homebrew-core/pull/129682

**Comment by Moulick** [comment]
waiting for a new release :)

**Comment by km-tr** [comment]
It's unfortunate that this was closed.

**Comment by jurgob** [comment]
any news on this? I switch between node versions a lot, this would be very helpfull
