### ISSUE TITLE
[Bug]: Remove the oc alias due to conflicts with openshift

### ISSUE THREAD

**Issue by Moulick** [di-sukharev/opencommit#144]
### Opencommit Version

2.0.0

### Node Version

v20.0.0

### NPM Version

9.6.4

### What OS are you seeing the problem on?

Mac

### What happened?

A bug happened! This is with reference to https://github.com/di-sukharev/opencommit/issues/118. Openshift already has `oc` as the cli for a very long time. Opencommit directly conflicts with that.

### Expected Behavior

`opencommit` to be installed successfully 

### Current Behavior

NPM is not able to install opencommit with systems that have openshift-cli already installed

### Possible Solution

opencommit should not install as `oc`

### Steps to Reproduce

1. Install openshift-cli
2. Attempt to install opencommit

### Relevant log output

```shell
❯ npm install -g opencommit
npm ERR! code EEXIST
npm ERR! path /opt/homebrew/bin/oc
npm ERR! EEXIST: file already exists
npm ERR! File exists: /opt/homebrew/bin/oc
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in: /Users/moulick.aggarwal/.npm/_logs/2023-04-26T14_39_57_399Z-debug-0.log
```

**Comment by Moulick** [comment]
This will also help in keeping consistency with https://github.com/di-sukharev/opencommit/issues/143 as else the command name in homebrew will be `opencommit` which would then not match documentation :(

**Comment by di-sukharev** [comment]
thanks for the error message, will fix on weekend <3

**Comment by di-sukharev** [comment]
@Moulick bro, could you help me here pls and do a PR? <3

**Comment by Moulick** [comment]
@di-sukharev will try!

**Comment by Moulick** [comment]
@di-sukharev Checkout https://github.com/di-sukharev/opencommit/pull/165

**Comment by di-sukharev** [comment]
> @di-sukharev Checkout #165

few comments, will merge when done

**Comment by di-sukharev** [comment]
done
