### ISSUE TITLE
[BUG] Error: Request failed with status code 404

### ISSUE THREAD

**Issue by Asandolo** [di-sukharev/opencommit#148]
### Opencommit Version

2.0.4

### Node Version

18.12.1

### NPM Version

9.6.5

### What happened?

When i try to generate a commit i hve this error 
 Error: Request failed with status code 404

### Expected Behavior

Generate a commit message

### Current Behavior

Not gerating commit and trow an error 
oc

![image](https://user-images.githubusercontent.com/11891385/235099627-a0b51f44-4727-4e0d-92bf-7beaa22b7128.png)

### Steps to Reproduce

config openai api key
config emoji
switch to gpt4
try `oc` command

**Comment by di-sukharev** [comment]
tou sure you use right model name? `oc config set model=gpt-4`

**Comment by Asandolo** [comment]
> 

Yes 

![image](https://user-images.githubusercontent.com/11891385/235123780-e80a3507-d60d-4d29-b404-b239df6fe158.png)

**Comment by carloshpdoc** [comment]
Same error here.

**Comment by ghazialhouwari** [comment]
Same issue here.

.opencommit
```
OPENAI_API_KEY=MY_API_KEY
model=gpt-4
emoji=true
description=true
language=en
```

**Comment by mreduar** [comment]
This is probably because you do not have access to the GPT-4 beta.

**Comment by Asandolo** [comment]
> This is probably because you do not have access to the GPT-4 beta.

I have acces to gpt4

**Comment by martijnvanderlaan** [comment]
+1

Also get the 404 error, but not when I commit a few files at a time. Maybe something like a token limit?

**Comment by martijnvanderlaan** [comment]
FYI, I noticed that I also got the error when trying to commit a .pbxproj file

**Comment by di-sukharev** [comment]
@martijnvanderlaan thanks for help here, do you want to investigate and make a PR helping making the world a better place?

**Comment by MartinMinkov** [comment]
I had the same issue, which was an error on my part. I assumed that because I subscribe to ChatGPT, I would have API access to chat-gpt4 if I created an API key, but this is [not the case right now](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4). This is a user error on my part; I just want to remind anyone who looks at this issue to make sure you _actually_ have API access to gpt-4. :sweat_smile:

**Comment by di-sukharev** [comment]
guys, please confirm that you have gpt-4 access <3

**Comment by ghazialhouwari** [comment]
@di-sukharev as @MartinMinkov mentioned I thought I have an acces to gpt-4, but it turns out the API is a separate thing. My bad

**Comment by di-sukharev** [comment]
> @di-sukharev as @MartinMinkov mentioned I thought I have an acces to gpt-4, but it turns out the API is a separate thing. My bad

yep, thanks for update, if you have ChatGPT+ it doesnt mean you have `gpt-4 api` access

**Comment by damianlluch** [comment]
@di-sukharev

**Comment by di-sukharev** [comment]
@damianlluch ohh, i forgot about it ;)
