### ISSUE TITLE
Allow opencommit to be installed as a devDependency

### ISSUE THREAD

**Issue by 0xKrauser** [di-sukharev/opencommit#16]
The tool looks promising, but as an avid remote dev environment (think github codespaces, gitpod) user I find it hard to install and store config globally. 
I would probably need to make a custom image in order to restore the global environment each time I open the workspace.

Would you consider an .env fallback for the config values or something of sort in order to make this easier?

**Comment by di-sukharev** [comment]
`.env` fallback is great, `devDep` is also great, thanks. do you want to make a PR?

**Comment by 0xKrauser** [comment]
Sure! Tomorrow I will draft it up.
