### ISSUE TITLE
[Bug]:  Infinite Loop with status 400

### ISSUE THREAD

**Issue by Nasfame** [di-sukharev/opencommit#184]
### Opencommit Version

1.0.4

### Node Version

16

### NPM Version

8

### What OS are you seeing the problem on?

Other Linux Distro

### What happened?

A bug happened!

The job is running forever upon getting status 400 for OPENAI.

https://github.com/algFame/geektrust/actions/runs/5076912716/jobs/9119566057

### Expected Behavior

Should quit after a couple of tries 

### Current Behavior

Running indefinitely

### Possible Solution

- Setting timeouts for jobs in github workflows
- Setting timeouts and max retries in the cli

### Steps to Reproduce

Setting OCO_OPENAI_MAX_TOKENS>=2000 may generate this error.

Refer - OCO_OPENAI_MAX_TOKENS

### Relevant log output

```shell
Logs large - refer https://github.com/algFame/geektrust/actions/runs/5076912716/jobs/9119566057
```
Error: Request failed with status code 429
│
└  Retrying after sleeping for 65000
│
└  Error: Request failed with status code 429
```
```

**Comment by di-sukharev** [comment]
done #186
