### ISSUE TITLE
[Feature]: change alias from `oc` to `oco`

### ISSUE THREAD

**Issue by navarrothiago** [di-sukharev/opencommit#185]
### Description

In openshift world, the `oc` is the openshift command line tool. It would be good to change the alias from `oc` to `oco` to avoid conflict. 

### Suggested Solution

Change alias from `oc` to `oco`.

**Comment by di-sukharev** [comment]
done #178

**Comment by kraibse** [comment]
The README needs to be updated too since it still refers to the `oc` command. I was confused since I was used to it from an earlier version.

https://github.com/di-sukharev/opencommit/blob/a70b831f9d892fc306352e09f4344a01d3f94328/README.md?plain=1#L110

**Comment by 0x01001** [comment]
how to keep using oc command?
