### ISSUE TITLE
[Bug]: 'OPENAI_API_KEY' name is invalid

### ISSUE THREAD

**Issue by NorkzYT** [di-sukharev/opencommit#194]
### Opencommit Version

2.2.10

### Node Version

v18.15.0

### NPM Version

9.6.7

### What OS are you seeing the problem on?

Windows

### What happened?

When running the `opencommit` command or any associated command from the `README.md`, the observed behavior is as follows. The cause of this behavior is currently unclear, although it is possible that it may be attributed to a bug in the latest NPM version.

### Expected Behavior

```bash
│
└  No changes detected
```

### Current Behavior

```bash
└  'OPENAI_API_KEY' name is invalid, it should be either 'OCO_OPENAI_API_KEY' or it doesn't exist.

│
└  Manually fix the '.env' file or global '~/.opencommit' config file.
```

### Possible Solution

Currently not sure.

### Steps to Reproduce

Command(s) ran:
`opencommit`

**Comment by di-sukharev** [comment]
@NorkzYT i guess you updated to latest version, which is breaking change and uses different config and conflicts with old values, so removing the config and creating a new one will work. manually patching `~/.opencommit` file also works

**Comment by NorkzYT** [comment]
Understood, thank you.
Will test and advise.

**Comment by NorkzYT** [comment]
Issue resolved.

Ran the following command:
```bash
rm -rf ~/.opencommit 
```
