### ISSUE TITLE
[Bug]: Unable to config API_KEY

### ISSUE THREAD

**Issue by yonatan-rotem** [di-sukharev/opencommit#198]
### Opencommit Version

2.2.10

### Node Version

16.14.0

### NPM Version

9.6.5

### What OS are you seeing the problem on?

Windows

### What happened?

every command is outputting the same error:
```
—  'OPENAI_API_KEY' name is invalid, it should be either 'OCO_OPENAI_API_KEY' or it doesn't exist.
—  Manually fix the '.env' file or global '~/.opencommit' config file.
```
can't set the API KEY, even when i execute the command
```
 config set OCO_OPENAI_API_KEY=<API_KEY>
```
I'm getting the same error.

### Expected Behavior

Set the APIkey

### Current Behavior

Unable to Set the APIkey

**Comment by Tuanpluss02** [comment]
Just open the file path C:\Users<username>.opencommit and replace `OPENAI_API_KEY` with `OCO_OPENAI_API_KEY`, and `emoji` with `OCO_EMOJI`. This worked for me.

**Comment by yonatan-rotem** [comment]
works thanks
