### ISSUE TITLE
Internal error when generating commit message

### ISSUE THREAD

**Issue by kivircik-parantez** [di-sukharev/opencommit#21]
I am encountering an internal error when trying to generating commit message. The error message I received is " ✖ internal error, try again."

I am using OpenCommit version v1.1.10 and from VSCode bash terminal. I have already tried restart and reinstalling, but the error persists.
Error changed to : 
![image](https://user-images.githubusercontent.com/54854223/225288821-ceaca809-e3a9-458c-a952-afedea3f1c09.png)

Can someone please provide guidance on how to resolve this issue? Thank you.

**Comment by di-sukharev** [comment]
@kivircik-parantez hello 

does commiting smaller file works? maybe file is too big, it should be divided in chunks, but looks like there is a bug in this functionality

**Comment by di-sukharev** [comment]
and it's also a duplicate of https://github.com/di-sukharev/opencommit/issues/8

**Comment by kivircik-parantez** [comment]
@di-sukharev thanks for your answer, another smaller commit worked.
