### ISSUE TITLE
Language settings feature

### ISSUE THREAD

**Issue by rozekfr** [di-sukharev/opencommit#23]
Hello,
is it possible to add feature to set language of commit message? 

There are possibilities to change conversation's language in ChatGPT.

Thank you.

**Comment by AdrielBento** [comment]
I haven't fully looked at the source code yet, but I think it's possible. In assigning the `content` attribute, there could be a setting to determine which language the chat should use to create the messages. Example: `Use language ${config.language} to create commit messages` or something like that.

**Comment by di-sukharev** [comment]
@rozekfr @AdrielBento thanks for taking care <3

do you want to make a PR?

**Comment by rozekfr** [comment]
@AdrielBento I had the same idea how to change the code. I wanted to add only this code:

``${config?.language ? `Use ${config?.language} language`:  ''``

I suppose you already tried this approach too.

**Comment by rozekfr** [comment]
Just adding a screenshot of ChatGPT.  No context before.

<img width="662" alt="Snímek obrazovky 2023-03-16 v 20 54 45" src="https://user-images.githubusercontent.com/18688500/225737968-a5cc0f9d-195a-4879-be1f-41238c6fd37d.png">

**Comment by di-sukharev** [comment]
PR is merged <3
