### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by damianlluch** [di-sukharev/opencommit#234]
### Opencommit Version

.

### Node Version

Latest

### NPM Version

.

### What OS are you seeing the problem on?

Mac

### What happened?

Hi, I had started using this tool a few months ago, and it was working fine, no problems. Then it stopped working, and today I tried again and I got this message when I tried to generate the message.

### Expected Behavior

...

### Current Behavior

<img width="723" alt="image" src="https://github.com/di-sukharev/opencommit/assets/1463804/a5b20f85-63e0-4c0e-ad64-32c2ef2ce44f">

### Possible Solution

..

### Steps to Reproduce

I have installed the library and configured the apikey.

**Comment by di-sukharev** [comment]
hi @damianlluch is it still an issue?

**Comment by damianlluch** [comment]
@di-sukharev hello, yes of course, as I said, I've been using it since the beginning of the year and I've had this error for a couple of months now.
I've tried deleting it, and adding it again, but it's still the same. 
I don't know why.

**Comment by di-sukharev** [comment]
was resolved here #148 148
