### ISSUE TITLE
[Bug]: Incorrect documentation for OCO_MODEL variable

### ISSUE THREAD

**Issue by gudlyf** [di-sukharev/opencommit#237]
### Opencommit Version

2.4.2

### Node Version

N/A

### NPM Version

N/A

### What happened?

The README.md has an incorrect configuration declaration:

`oco config set OCO_OPENAI_API_KEY=gpt-4`

This should be:

`oco config set OCO_MODEL=gpt-4`

### Expected Behavior

`oco config set OCO_MODEL=gpt-4`

### Current Behavior

`oco config set OCO_OPENAI_API_KEY=gpt-4`

Attempting this will result in an error.

**Comment by di-sukharev** [comment]
fixed, thanks!
