### ISSUE TITLE
[Feature]: Documentation Request: Clarification on OCO_MESSAGE_TEMPLATE_PLACEHOLDER Usage

### ISSUE THREAD

**Issue by EwiththeBowtie** [di-sukharev/opencommit#241]
### Description

First off, I'd like to say how much I've enjoyed exploring the `opencommit` tool – it's evident that a lot of thought and effort has gone into its development. While diving in, I stumbled upon the `OCO_MESSAGE_TEMPLATE_PLACEHOLDER` feature. The current documentation reads:

```
To include a message in the generated message, you can utilize the template function! For instance:

oco '$msg #205’
opencommit examines placeholders in the parameters, allowing you to append additional information before and after the placeholders, such as the relevant Issue or Pull Request. Similarly, you have the option to customize the OCO_MESSAGE_TEMPLATE_PLACEHOLDER configuration item, for example, simplifying it to $m!"
```

I genuinely appreciate the guidance provided. However, I felt a bit uncertain about some aspects and believe that a touch more clarity could help users like me get the most out of this fantastic tool.

### Suggested Solution:

- **Enhance the Documentation**: Building upon the existing documentation could make a world of difference:
  - A deeper dive into the "template function" would be enlightening.
  - Breaking down the example `oco '$msg #205’` to clarify its components could be beneficial for users.
  - Expanding on the "placeholders" concept with more examples would offer a richer understanding.
  - Some insights into the transition from `$msg` to `$m` in the `OCO_MESSAGE_TEMPLATE_PLACEHOLDER` configuration would be helpful.
- **Examples**: Including real-world examples can be a game-changer, helping users visualize and understand the feature's full potential.
- **External Links**: If there are related external resources or tutorials, those would be valuable additions, offering users a comprehensive learning experience.

### Alternatives:

- **Reference to Standard Git Feature**: I'm wondering if the `OCO_MESSAGE_TEMPLATE_PLACEHOLDER` or the template function might be rooted in a standard Git feature I'm unfamiliar with. If so, a nod to the official Git documentation or other trusted resources would be a wonderful touch, helping bridge any knowledge gaps.

### Additional Context:

I believe these suggestions come from a place of wanting to see this already impressive tool become even more user-friendly. Thanks for considering my feedback, and keep up the great work!

**Comment by EwiththeBowtie** [comment]
Certainly! Here's a comment that addresses the GitHub issue based on the provided code, excluding point 4:

---
Thank you for your detailed feedback on the `opencommit` tool and its `OCO_MESSAGE_TEMPLATE_PLACEHOLDER` feature. I've taken a closer look at the codebase to understand its implementation and how it relates to your feedback:

1. **OCO_MESSAGE_TEMPLATE_PLACEHOLDER Feature**:
   - Your issue highlights the `OCO_MESSAGE_TEMPLATE_PLACEHOLDER` feature, which is designed to allow users to embed a custom message within the generated commit message using a template function.
   - In the codebase, this feature's implementation is evident in the line from config.ts:
     ```javascript
     commitMessage = messageTemplate.replace(
        config?.OCO_MESSAGE_TEMPLATE_PLACEHOLDER,
        commitMessage
      );
     ```
     This line is responsible for replacing the placeholder in the `messageTemplate` with the actual `commitMessage`.

2. **Documentation Clarity**:
   - You've rightly pointed out areas in the documentation that could benefit from added clarity, especially regarding the "template function" and the transition from `$msg` to `$m`.
   - While the code doesn't directly touch upon documentation, it does showcase the backend implementation of this feature. This can be a valuable reference when enhancing the documentation.

3. **Commit Message Generation**:
   - The function `generateCommitMessageFromGitDiff` in the codebase is designed to generate a commit message based on a git diff, and it potentially leverages the `OCO_MESSAGE_TEMPLATE_PLACEHOLDER` feature.
   - Your example `oco '$msg #205’` seems to be a command that taps into this feature. The provided code likely represents the backend mechanics of such commands.

5. **Committing with the Message**:
   - Once the user confirms, the code proceeds to commit with the generated message using the `git commit` command.
   - This ties back to your point about understanding the feature's full potential. By enhancing the documentation and providing clearer examples, users will likely feel more confident in using the generated messages for their commits.

In essence, the codebase offers a deep dive into the implementation details of the `OCO_MESSAGE_TEMPLATE_PLACEHOLDER` feature and the process of generating and committing with a message. Your feedback is invaluable, and using the code as a reference, we can certainly work towards addressing the concerns you've raised and improving the overall user experience.

Thanks again for your insights!

**Comment by di-sukharev** [comment]
@EwiththeBowtie thank you for your thoughtful contribution! Hope we collaborate on other features soon.

the #242 PR was merged <3
