### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'OCO_OPENAI_BASE_PATH')

### ISSUE THREAD

**Issue by danielorozco06** [di-sukharev/opencommit#251]
### Opencommit Version

3.0.3

### Node Version

v16..20.2

### NPM Version

8.19.4

### What OS are you seeing the problem on?

Other Linux Distro

### What happened?

I am using Ubuntu 22.04 on WSL v2

When launch this command:
oco config set OCO_OPENAI_API_KEY=APIKEY

I have this error:
┌  opencommit — config
│
└  ✖ TypeError: Cannot read properties of undefined (reading 'OCO_OPENAI_BASE_PATH')

That problem was not presented before. Only when reinstall oco after a OS reformatting.

### Expected Behavior

That I can set my openai api key

### Current Behavior

There is an error when set openai api key

**Comment by enesj** [comment]
Me to on MacBook Pro M1

**Comment by roonie007** [comment]
+1

**Comment by Emkacf** [comment]
Me too, MacBook Pro M2

**Comment by di-sukharev** [comment]
Will fix this week, thanksOn 11 Sep 2023, at 16:41, Emilia Heller-Mrotek ***@***.***> wrote:﻿
Me too, MacBook Pro M2

**Comment by AlexandrosMelissas** [comment]
@di-sukharev  Is there a temporary fix until it's fixed?

**Comment by Emkacf** [comment]
> @di-sukharev Is there a temporary fix until it's fixed?

For me setting up .env per repository works fine, there you can add your api key

**Comment by rahul-ponce** [comment]
+1

**Comment by ArnaudGadbin2** [comment]
+1

**Comment by VictorGuillen-SpardaSoft** [comment]
+1

**Comment by nallenscott** [comment]
```shell
echo OCO_OPENAI_API_KEY=<your OpenAI API token> >> ~/.opencommit
```

**Comment by deividgp** [comment]
Me too, Windows 10.

**Comment by evanmarshall-dev** [comment]
> ### Opencommit Version
> 3.0.3
> 
> ### Node Version
> v16..20.2
> 
> ### NPM Version
> 8.19.4
> 
> ### What OS are you seeing the problem on?
> Other Linux Distro
> 
> ### What happened?
> I am using Ubuntu 22.04 on WSL v2
> 
> When launch this command: oco config set OCO_OPENAI_API_KEY=APIKEY
> 
> I have this error: ┌ opencommit — config │ └ ✖ TypeError: Cannot read properties of undefined (reading 'OCO_OPENAI_BASE_PATH')
> 
> That problem was not presented before. Only when reinstall oco after a OS reformatting.
> 
> ### Expected Behavior
> That I can set my openai api key
> 
> ### Current Behavior
> There is an error when set openai api key
> 
> ### Possible Solution
> _No response_
> 
> ### Steps to Reproduce
> _No response_
> 
> ### Relevant log output
> _No response_

Me, too on MacBook Intel

**Comment by evanmarshall-dev** [comment]
> ```shell
> ```shell
> echo OCO_OPENAI_API_KEY=<your OpenAI API token> >> ~/.opencommit
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> .. will get things working.
> ```

Worked for me! Thank you.

**Comment by di-sukharev** [comment]
getting to it tomorrow, too busy

**Comment by di-sukharev** [comment]
@danielorozco06 @enesj @roonie007 hey guys, please install 3.0.4 and tell me if it works: `npm i -g opencommit@latest`

**Comment by deividgp** [comment]
> @danielorozco06 @enesj @roonie007 hey guys, please install 3.0.4 and tell me if it works: `npm i -g opencommit@latest`

It works for me now, appreciated. 😄

**Comment by di-sukharev** [comment]
@deividgp great <3

**Comment by StephaneLASOUR** [comment]
not working for me : 
'OCO_OPENAI_API_KEY' name is invalid, it should be either 'OCO_OCO_OPENAI_API_KEY' or it doesn't exist.
context:
I'm using nvm

**Comment by di-sukharev** [comment]
@StephaneLASOUR have you just updated to latest version from some really old one?

**Comment by StephaneLASOUR** [comment]
> @StephaneLASOUR have you just updated to latest version from some really old one?

Yes I did, from 1.1.24

**Comment by di-sukharev** [comment]
@StephaneLASOUR major versions are breaking changes, so you should remove `~.opencommit` file and install and config everything again

**Comment by enesj** [comment]
> Me to on MacBook Pro M1

Works now. Thanks.
