### ISSUE TITLE
(love) Just to tell you how great your software is

### ISSUE THREAD

**Issue by aleluff** [di-sukharev/opencommit#260]
### Opencommit Version

1.0.0

### Node Version

20.0.0

### NPM Version

9.5.0

### What happened?

The real issue is maybe that opensource developers don't receive enough gratification.
Thanks to you, creator can build better software

Have a nice day =)

### Expected Behavior

Keep the flame

### Current Behavior

Perfection

**Comment by di-sukharev** [comment]
@aleluff <3 thank you!

**Comment by aleluff** [comment]
<3
