### ISSUE TITLE
[Feature]: Git log generator

### ISSUE THREAD

**Issue by aleluff** [di-sukharev/opencommit#264]
### Description

Here is a script I use to auto generate basic HTML changelog from git history : https://gitlab.com/web-db/public/-/blob/main/changelog.js

### Suggested Solution

I thought you can make a link somewhere to help people

**Comment by di-sukharev** [comment]
@aleluff do you want to do a PR?

**Comment by di-sukharev** [comment]
i would just run it through npm scripts

**Comment by aleluff** [comment]
I do the PR and you do the README ? =)

I think of a user who tell to himself, that oco and the script can be a real production solution together (like I do)

**Comment by aleluff** [comment]
Done
