### ISSUE TITLE
[Bug]: Git error when use OCO_MESSAGE_TEMPLATE_PLACEHOLDER

### ISSUE THREAD

**Issue by mdespeuilles** [di-sukharev/opencommit#278]
### Opencommit Version

3.0.4

### Node Version

18.18.2

### NPM Version

9.8.1

### What OS are you seeing the problem on?

Mac

### What happened?

I've configured open commit to use the Message Template Placeholder by default: 

`OCO_MESSAGE_TEMPLATE_PLACEHOLDER=$msg
`
When I try to launch oco with a custom message : 

`oco '#111 $msg'
`
I get this error: 

```
└ ✖ Command failed with exit code 1: git commit -m #111 ⬆️ chore(package.json)...... #111 $msg
error: pathspec '#111 $msg' did not match any file(s) known to git
```

### Expected Behavior

Commit messages is generated successfully.

### Current Behavior

Git error message : 

```
└ ✖ Command failed with exit code 1: git commit -m #111 ⬆️ chore(package.json)...... #111 $msg
error: pathspec '#111 $msg' did not match any file(s) known to git
```

**Comment by di-sukharev** [comment]
reopening, will take a look at this

**Comment by di-sukharev** [comment]
update to `npm i -g opencommit@latest`
