### ISSUE TITLE
generated first line is too long

### ISSUE THREAD

**Issue by xpokor02** [di-sukharev/opencommit#29]
I use vs code and hook and generated message has fist line 177 characters long but imho git has limit 72 
Thanks

**Comment by geoynomous** [comment]
Was about to post the same! And it's also only "one" of the changes - I'd prefer it is a summary of the changes

It seems to me that oc is good when only one file is changed, but when there are changes to multiple files it's a bit confused. It seems to handle each file individually

**Comment by di-sukharev** [comment]
there is no limit for 72. as for the 1 summarized message — do you want to investigate the code and do a PR?
