### ISSUE TITLE
[Feature]: Support Custom API Key Formats and Server Addresses

### ISSUE THREAD

**Issue by XiaomaiTX** [di-sukharev/opencommit#291]
### Description

I would like to request the addition of a feature to allow for the customization of API key formats and the API server address, providing flexibility for users with diverse API key structures.

### Suggested Solution

Introduce configuration options to set custom API key formats and a custom API server address. This can be achieved by adding commands similar to:

`oco config set OCO_CUSTOM_API_KEY_PATTERN=<custom_key_pattern>`

`oco config set OCO_CUSTOM_API_SERVER=<custom_server_address>`

Where <custom_key_pattern> represents the user-defined API key pattern, and <custom_server_address> represents the user-defined API server address.

### Alternatives

Upon setting custom API key formats and a server address, OpenCommit should utilize the specified formats for API requests instead of the default settings.

**Comment by di-sukharev** [comment]
reopening, will take a look at this

**Comment by sebastienfi** [comment]
Currently OpenCommit supports two engines: 
- OpenAI, which have a specific pattern for validating API keys input by OCO users. This service can be proxied (eventually including a custom basepath).
- Ollama which can be hosted anywhere, and does not have a specific pattern for the API key.

```typescript
[CONFIG_KEYS.OCO_OPENAI_API_KEY](value: any, config: any = {}) {
  //need api key unless running locally with ollama
  validateConfig(
    'API_KEY',
    value || config.OCO_AI_PROVIDER == 'ollama',
    'You need to provide an API key'
  );
  validateConfig(
    CONFIG_KEYS.OCO_OPENAI_API_KEY,
    value.startsWith('sk-'),
    'Must start with "sk-"'
  );
  validateConfig(
    CONFIG_KEYS.OCO_OPENAI_API_KEY,
    config[CONFIG_KEYS.OCO_OPENAI_BASE_PATH] || value.length === 51,
    'Must be 51 characters long'
  );

  return value;
},
```
@XiaomaiTX Could you please elaborate on the feature you would like to have? It seems you would like to have the ability to make calls to an LLM API specifying the URL of its backend, possibly another engine. Please enlighten us.

**Comment by XiaomaiTX** [comment]
@sebastienfi Another friend and I developed a project called [ChatNio](https://github.com/Deeptrain-Community/chatnio), which is an AI model aggregation platform, which means that users can access different back-end AI services supported by ChatNio through a unified API interface. The use of ChatNio's API interface is the same as that of OpenAI's API interface, but the length of the custom API key we provide is different from that of the official API Key of OpenAI, which causes problems when I want to connect the ChatNio service to opencommit in OpenAI format.

**Comment by sebastienfi** [comment]
I see. Then this is simply about removing the business rule which validates for OpenAI API Key format? The code that needs to change is the one I provided earlier, removing any validation on the OpenAI API Key. Anyway, I don't think we should validate this key, that seems out of scope for OCO. @XiaomaiTX Would you like to submit a PR?

**Comment by XiaomaiTX** [comment]
@sebastienfi It's my honor if I can submit a PR for this project!❤️

Can I submit PR tomorrow or the day after tomorrow? I'm a little busy today.

**Comment by XiaomaiTX** [comment]
I haven't been here for a long time, forgot to submit a commit, and am glad to see that [commit#e19305d](https://github.com/di-sukharev/opencommit/commit/e19305dee280dc7598d196653f04b6128662666f) resolved this issue
