### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by pyoner** [di-sukharev/opencommit#298]
Hi @di-sukharev!

Thank you for the project, but I see that many PRs or ISSUEs have been closed with labels [no-pr-activity](https://github.com/di-sukharev/opencommit/pulls?q=is%3Apr+is%3Aclosed+label%3Ano-pr-activity) and [no-issue-activity](https://github.com/di-sukharev/opencommit/issues?q=is%3Aissue+is%3Aclosed+label%3Ano-issue-activity)

Do you have any plans for the future to maintain the project?

**Comment by di-sukharev** [comment]
Hi, just merged few prs yesterday, thanks for the catch, i will review the closed PRs

**Comment by di-sukharev** [comment]
reopened the important issues
