### ISSUE TITLE
I can't figure out what internal error is

### ISSUE THREAD

**Issue by GuardianOfGods** [di-sukharev/opencommit#3]
![image](https://user-images.githubusercontent.com/52252046/224292585-c2a48560-273b-458c-b384-f2004e368949.png)

**Comment by di-sukharev** [comment]
i think it's openai api "too many requests error"

**Comment by brunoricardosecco** [comment]
Same here 🤔

**Comment by di-sukharev** [comment]
guys, do `opencommit config set OPENAI_API_KEY=<your_api_key>` and update the lib with `npm i -g opencommit`

**Comment by mikkelhartung** [comment]
Also, remember to add a payment method in OpenAI folks 💸 
It would make sense to make [this section](https://github.com/di-sukharev/opencommit#payments) in the docs a bit more clear about this.

**Comment by brunoricardosecco** [comment]
@mikkelhartung is it necessary to add a payment method? If the answer is yes, that's my error I guess

**Comment by mikkelhartung** [comment]
@brunoricardosecco OpenAI is a pay-as-you-go service, so I would expect that the account that the API key is attached to should have a payment method in order for it to work 😄 

I got the same error initially, but then added payment information and after a few minutes I was up and running.

**Comment by brunoricardosecco** [comment]
Thank you so much!

**Comment by GuardianOfGods** [comment]
I already setup the config, I try to commit another code with short feature and it works. It's show "Internal Error, try again" even when I forgot to pull from remote. But here is another error and i still don't know what error is.

**Comment by di-sukharev** [comment]
there is some error handling, update the package `npm i -g opencommit`

**Comment by GuardianOfGods** [comment]
Now I can see the error. Because of causing too many request so it can't generate the commit. I add 1 package in project but open ai can't summary. Hope Open AI can do it better or you can do it better. If there are no more argument about the issue, I will close this.

**Comment by di-sukharev** [comment]
@GuardianOfGods close pls <3
