### ISSUE TITLE
Accept / Reject + Edit

### ISSUE THREAD

**Issue by geoynomous** [di-sukharev/opencommit#30]
Currently one can only Accept or Reject the proposed commit message - add an option to **edit** the message (using $EDITOR)

**Comment by di-sukharev** [comment]
if you set `oc hook set` it will integrate into your pipeline using "$EDITOR" var. e.g. using VScode — (after hook is set) you run `git commit` and it suggests you OpenCommit mesasge. Or you can submit an empty commit message through Source Control tab and it will do the same
