### ISSUE TITLE
[Feature]: Claude 3 Support

### ISSUE THREAD

**Issue by km-tr** [di-sukharev/opencommit#312]
### Description

I think it would be better to support Opus, Sonnet, and Haiku for Claude 3.

### Suggested Solution

In particular, I believe some people may prefer to use Haiku because it is cheaper and faster than ChatGPT 3.5 Turbo.

### Additional Context

https://github.com/anthropics/anthropic-sdk-typescript

**Comment by di-sukharev** [comment]
wanna do a PR?

**Comment by km-tr** [comment]
Yes, I would like to address this. It will be difficult this week as I am quite busy, but I generally have a clear idea of the approach to take.

**Comment by di-sukharev** [comment]
ping me here if you need any help <3

Sent via Superhuman ( ***@***.*** )
