### ISSUE TITLE
[Bug]: Setting `OCO_ONE_LINE_COMMIT=true` generates a multi-line message

### ISSUE THREAD

**Issue by redryerye** [di-sukharev/opencommit#315]
### Opencommit Version

1.0.2

### Node Version

20.8.0

### NPM Version

10.0.1

### What happened?

Setting `OCO_ONE_LINE_COMMIT=true` generates a multi-line message, making it not much different from setting `OCO_ONE_LINE_COMMIT=false.`

### Expected Behavior

Generates single line message when `OCO_ONE_LINE_COMMIT=true` is set.

### Current Behavior

Setting `OCO_ONE_LINE_COMMIT=true` generates a multi-line message.

### Possible Solution

Iterate the [prompt](https://github.com/di-sukharev/opencommit/blob/0ac7211ff702036e3656170ec1a1a51eef29703f/src/modules/commitlint/prompts.ts#L270)

**Comment by br-programmer** [comment]
duplicate issue #314

**Comment by di-sukharev** [comment]
will be resolved [here](https://github.com/di-sukharev/opencommit/issues/409#issuecomment-2333849088)
