### ISSUE TITLE
[Bug]: Unsupported config key OCO_OPENAI_API_KEY: Must be 51 characters long

### ISSUE THREAD

**Issue by PMassicotte** [di-sukharev/opencommit#326]
### Opencommit Version

1.0.2

### Node Version

18.20.2

### NPM Version

10.5.0

### What OS are you seeing the problem on?

Other Linux Distro

### What happened?

openai pushing to use project based keys which are longer than the 51 characters expected by opencommit

![image](https://github.com/di-sukharev/opencommit/assets/4519221/22cdacb1-f3a4-45d8-b7ce-5af322d01585)

### Expected Behavior

Able to use the new key format

### Current Behavior

> Unsupported config key OCO_OPENAI_API_KEY: Must be 51 characters long

**Comment by di-sukharev** [comment]
true, looks like new openai tokens can now be larger than 51 chars, we should get rid of the 51 length validation, any volunteers for a PR? should be a 1 liner, will look into it on the weekend myself if no PR is opened earlier

**Comment by di-sukharev** [comment]
pls keep it opened before new version is published

**Comment by di-sukharev** [comment]
update the latest version just merged https://github.com/di-sukharev/opencommit/pull/412

run `npm i -g opencommit@latest`
