### ISSUE TITLE
Feature request: add a dry run mode

### ISSUE THREAD

**Issue by nader-zouaoui** [di-sukharev/opencommit#33]
Does it make sense to add a dry run mode to the `oc` command?

It goes like: 
input: 
```sh
oc --dry-run
```
output:
```
commit message: 
feat(someFeature): some message

git command:

git commit -m "feat(someFeature): some message"
```

**Comment by di-sukharev** [comment]
it's possible in the new version, you can pass any arguments to `oc <...arguments>` that you can pass to `git commit <...arguments>`
