### ISSUE TITLE
[Bug]: Punycode warning

### ISSUE THREAD

**Issue by zain** [di-sukharev/opencommit#334]
### Opencommit Version

3.0.15

### Node Version

21.7.3

### NPM Version

10.5.0

### What OS are you seeing the problem on?

Mac

### What happened?

Seeing this warning when running any oco commends:

```
(node:39887) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

### Expected Behavior

No warning

### Current Behavior

Is a warning

**Comment by di-sukharev** [comment]
hi @zain thanks for the report, do you want to take a look at it an submit a PR making world a better place together?

**Comment by bitfactory-robin-martijn** [comment]
I'm happy to fix this as I'm encountering the same issue. Is there a contribution guide, or any instructions on how to set this up properly?

**Comment by di-sukharev** [comment]
yes, please look into .github/CONTRIBUTION.md

**Comment by btglr** [comment]
The deprecation warning comes from `@anthropaic-ai/sdk` and `openai` having dependencies on older `node-fetch` versions. Unfortunately updating those packages and especially the `openai` package requires rewriting the API logic.

**Comment by di-sukharev** [comment]
@btglr hi there 👋 could you please share what exactly needs to be rewritten? i will manage, it finally started to annoy me

**Comment by di-sukharev** [comment]
should be fixed with a new version. please update and follow up @zain

**Comment by minarc** [comment]
@di-sukharev Got again in new version at 3.1.1 node version is 22.7.0

```
(node:66000) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by di-sukharev** [comment]
thanks @minarc, will investigate and reopen the issue if we get more people here

**Comment by aldinokemal** [comment]
<img width="1012" alt="image" src="https://github.com/user-attachments/assets/f241ac95-1003-4d00-9d07-72878d69a1bc">
still happen in my end using node `v22.9.0` and oco `3.2.2`
