### ISSUE TITLE
[Bug]: Always used full list of emoji

### ISSUE THREAD

**Issue by stanislavlysenko0912** [di-sukharev/opencommit#354]
### Opencommit Version

3.0.16

### Node Version

21.7.1

### NPM Version

10.5.0

### What OS are you seeing the problem on?

Mac

### What happened?

When using emojis, always used full list from`prompts.ts`.

### Expected Behavior

The use of `--fgm` affected the result

### Current Behavior

When i just run `oco` command, i got:
```bash
➜  repository git:(master) ✗ oco
(node:72947) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
┌  open-commit
│
◇  1 staged files:
  src/pages/Game1/Game1Page.css
│
◇  📝 Commit message generated
│
└  Generated commit message:
——————————————————
💄 (Game1Page.css): add margin to .answer-button for improved spacing
```

When use with `--fgm` i got same:
```bash
➜  repository git:(master) ✗ oco --fgm
(node:73066) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
┌  open-commit
│
◇  1 staged files:
  src/pages/Game1/Game1Page.css
│
◇  📝 Commit message generated
│
└  Generated commit message:
——————————————————
💄 (Game1Page.css): add margin to .answer-button for improved spacing
```

**Comment by di-sukharev** [comment]
hi @stanislavlysenko0912, what exactly did you expect to see in your case when used `--fgm`?

**Comment by stanislavlysenko0912** [comment]
I wilI don't want to breed issues, so I'll close it.
I wanted to somehow get rid of different emoji and use only some standard ones. It's probably not relevant now. I just switch off emoji :D
