### ISSUE TITLE
[Feature]: Possible to use with Fork?

### ISSUE THREAD

**Issue by YipingRuan** [di-sukharev/opencommit#359]
### Description

https://fork.dev/

Is it possible to integrate with Fork's custom command? The commit message generation is an interactive session, it is not obvious how to do it.

![image](https://github.com/di-sukharev/opencommit/assets/5492274/fb2e29f7-cfaa-4400-8ef8-52fcf77fd9b5)

### Suggested Solution

This is a question..

**Comment by di-sukharev** [comment]
opencommit is a cli that runs js under the hood, i dont use fork, you can try to test it by starting with `oco hook set` command sources in `src/commands/githook.ts` — this is integrated into vscode Source Control pipeline and prob can be used to embed into fork.dev
