### ISSUE TITLE
[Feature]: Support for gpt-4o

### ISSUE THREAD

**Issue by cortex225** [di-sukharev/opencommit#360]
### Description

Can we have a support for model gpt-4o ?

### Suggested Solution

Can we have a support for model gpt-4o ?

**Comment by jakoberpf** [comment]
We/I are/am using opencommit with gpt4o already and it works fine. Not sure if this helps as feedback.

**Comment by Meowzz95** [comment]
set it like this in `.opencommit` and it works 

`OCO_MODEL=gpt-4o`

**Comment by matscube** [comment]
@cortex225 
Please ensure that you are using the latest version of OpenCommit. The current latest version appears to be **3.0.16**, which supports gpt-4o.

version check command: `oco --version`

If you are using the `oco hook`, it's important to verify that the installed oco's script version for the git hook is up-to-date. Please note that when you update OpenCommit, the hook script does not automatically update. Therefore, you will need to manually update the hook script.

git hook script: `.git/hooks/prepare-commit-msg`

**Comment by cortex225** [comment]
@matscube 
yes, I have de right version ` oco --version
3.0.16` and I got the same message here `  InstaHr/Views/Shared/PartialViews/Dashboard/Invoices/_InvoicesBalance.cshtml
│
◇  📝 Commit message generated
│
└  Generated commit message:
——————————————————
💄 (InvoicesBalance.cshtml): remove unnecessary color-white class from icon to improve visual consistency
💄 (InvoicesBalance.cshtml): fix indentation for better readability
——————————————————

│
│
◇  📝 Commit message generated
│
└  ✖ Command failed with exit code 1: git commit -m 💄 (InvoicesBalance.cshtml): remove unnecessary color-white class from icon to improve visual consistency
💄 (InvoicesBalance.cshtml): fix indentation for better readability
│
└  ✖ Unsupported config key OCO_MODEL: gpt-4o is not supported yet, use 'gpt-4', 'gpt-3.5-turbo-16k' (default), 'gpt-3.5-turbo-0613' or 'gpt-3.5-turbo'
`

**Comment by matscube** [comment]
@cortex225 
If possible, could you share the configuration of the config files you are using (`.opencommit` and local `.env`)?
The `.opencommit` file I am using is as follows. Also, I am not using a local .env file.
With this configuration, the `oco` command is working correctly.

```
OCO_OPENAI_API_KEY=sk-..........
OCO_MODEL=gpt-4o
OCO_LANGUAGE=en
OCO_MESSAGE_TEMPLATE_PLACEHOLDER=$msg
OCO_PROMPT_MODULE=conventional-commit
```


Additionally, would it be possible to create a new git repository and test whether it works there?
```
$ mkdir test-dir
$ cd test-dir
$ git init
$ echo 'test' > test
$ oco
```

**Comment by XiaomaiTX** [comment]
Hi, @cortex225 

#365 

Waiting for review

Best regards.

**Comment by di-sukharev** [comment]
@cortex225 you need to check `.opencommit` folder in the specific version of your node's `node_modules`, it may be that you are using old version in e.g. node v18 instead of v20, just remove all `.opencommit` folders in every global `node_modules` packages and install opencommit from scratch

**Comment by di-sukharev** [comment]
#366 v3.0.17 shipped

**Comment by cortex225** [comment]
@di-sukharev I have node v21.7.2, And I installed opencommit from scratch, it always same result 😞

**Comment by di-sukharev** [comment]
@cortex225 did you look into your global node_modules? please do, there are packages for every version, remove opencommit folder inside every node version folder

**Comment by cortex225** [comment]
@di-sukharev Thanks, it's work 🎉
