### ISSUE TITLE
[Feature]: support model gpt-4o-mini

### ISSUE THREAD

**Issue by tianlelyd** [di-sukharev/opencommit#364]
### Description

OpenAI has released the GPT-4O-Mini model, which is fast and cheap, but at the moment OpenCommit is not available!

### Suggested Solution

The OCO_MODEL configuration item in the configuration file supports GPT-4O-mini：
```
OCO_MODEL=gpt-4o-mini
```

**Comment by XiaomaiTX** [comment]
Hi, @tianlelyd 

https://github.com/di-sukharev/opencommit/pull/365

Waiting for review

Best regards.

**Comment by di-sukharev** [comment]
#366 v3.0.17 shipped
