### ISSUE TITLE
[Bug]: cannot type the passphrase for the ssh key when i git push

### ISSUE THREAD

**Issue by banoni-dev** [di-sukharev/opencommit#369]
### Opencommit Version

3.0.16

### Node Version

20.15.1

### NPM Version

10.7.0

### What OS are you seeing the problem on?

Other Linux Distro

### What happened?

after generating the commit  message and accepting it. it asks for pushing but i am using ssh key so i should type the passphrase but i can't

![image](https://github.com/user-attachments/assets/29ce5e9e-6f64-491e-9383-c82891f01407)

### Expected Behavior

hwn i choose to push the cli asks for the passphrase and i can type it

### Current Behavior

it shows the msg to type the passphrase but nothing is typed

**Comment by matscube** [comment]
@banoni-dev 
Hi,
Maybe this isn't the answer you expected, but you can skip the git-push step by using the `OCO_GITPUSH` environment variable.
If you set `OCO_GITPUSH` to `false`, the oco CLI will not automatically push your branch after generating the commit.

```sh
# ~/.opencommit

OCO_GITPUSH=false
```

**Comment by di-sukharev** [comment]
@matscube hi, thank you for the help. I think what we need is to pipe stdout into the cli logs somehow, if you have any ideas — please share in this thread <3

**Comment by matscube** [comment]
@di-sukharev Hi,
By using the `stdin` option of `execa`, it might be possible to input the SSH key password during the `git push` process of `oco` and pipe it to the git command.

However, if users cache the password with `ssh-agent`, they won't be prompted for a password during `git push`.
This issue could be addressed by caching the password in advance using `ssh-add`.

The use case for piping password input via stdin might be limited, but if there's demand, I can look into implementing this feature. What do you think?

* https://github.com/sindresorhus/execa/tree/v7.0.0?tab=readme-ov-file#stdio
* https://nodejs.org/api/child_process.html#child_process_options_stdio

**Comment by di-sukharev** [comment]
Takanori, please do, it would be a great improvement. Lets pipe all the
stdout, it is good to also see husky and other pre-commit/push pipeline
logs

**Comment by di-sukharev** [comment]
@banoni-dev please refer to this comment https://github.com/di-sukharev/opencommit/issues/369#issuecomment-2246805940 as a workaround
