### ISSUE TITLE
[Bug]: Unsupported config key OCO_MODEL: gpt-4o-mini is not supported yet

### ISSUE THREAD

**Issue by banoni-dev** [di-sukharev/opencommit#370]
### Opencommit Version

3.0.16

### Node Version

20.15.1

### NPM Version

10.7.0

### What OS are you seeing the problem on?

Other Linux Distro

### What happened?

i want to use gpt-4o-mini but i got this error and in the documentation it's mentioned that i can  use it 
i tried to set up it manually but modifying the .opencommit file but got the same error

![image](https://github.com/user-attachments/assets/71f42604-0786-4669-82bc-43694a3206c5)

![image](https://github.com/user-attachments/assets/399ecc5f-4cc2-43d0-a589-b8f13bd1088b)

### Expected Behavior

i except to the model to work

### Current Behavior

i get error when i choose the gpt-4o-mini

**Comment by sinsky** [comment]
Not supported in version 3.0.16, please update to 3.0.17.

**Comment by banoni-dev** [comment]
> Not supported in version 3.0.16, please update to 3.0.17.

thanks that solved the problem
