### ISSUE TITLE
[Bug]: zh_CN.json is wrong

### ISSUE THREAD

**Issue by XYCode-Kerman** [di-sukharev/opencommit#372]
### Opencommit Version

3.0.17

### Node Version

18.19.1

### NPM Version

10.2.4

### What OS are you seeing the problem on?

Other Linux Distro

### What happened?

zh_CN.json is wrong.

### Expected Behavior

```json
{
  "localLanguage": "简体中文",
  "commitFix": "fix(server.ts)：将端口变量从小写port改为大写PORT",
  "commitFeat": "feat(server.ts)：添加对process.env.PORT环境变量的支持",
  "commitDescription": "现在端口变量被命名为PORT，这提高了命名约定的一致性，因为PORT是一个常量。环境变量的支持使应用程序更加灵活，因为它现在可以通过process.env.PORT环境变量在任何可用端口上运行。"
}
```

### Current Behavior

commit message not follow conventional commits in Chinese.

**Comment by di-sukharev** [comment]
@XYCode-Kerman hi, thank you for the catch! do you want to submit a PR?

**Comment by XYCode-Kerman** [comment]
> @XYCode-Kerman hi, thank you for the catch! do you want to submit a PR?

OK, I will(I am busy these days, sorry for my late)

**Comment by di-sukharev** [comment]
the PR is merged, please follow up
