### ISSUE TITLE
[Feature]: Support Flowise as an AI provider

### ISSUE THREAD

**Issue by JMN09** [di-sukharev/opencommit#373]
### Description

The feature to be implement would allow the integration of flowise as an AI provider. Flowise allows building fast AI solution using a simple UI. It supports a wide spectrum of applications from quick prototyping, to building industry grade solutions.

### Suggested Solution

Add an AiEngine class that communicates with Flowise's endpoint.

**Comment by di-sukharev** [comment]
merged, will be released in the next version

**Comment by di-sukharev** [comment]
@JMN09 also mentioning it here.

there was a breaking change to how flowise url is expected, please see here flowi
