### ISSUE TITLE
[Bug]: Error: The text contains a special token that is not allowed: <|endoftext|>

### ISSUE THREAD

**Issue by hochmannA1** [di-sukharev/opencommit#377]
### Opencommit Version

3.0.17

### Node Version

v20.12.2

### NPM Version

10.5.0

### What OS are you seeing the problem on?

Other Linux Distro

### What happened?

When using oco to generate commit message with files containing the string "<|endoftext|>" oco fails with the following error:

◓  Generating commit message..   
│
└  ✖ Error: The text contains a special token that is not allowed: <|endoftext|>

### Expected Behavior

opencommit should generate a commit message even though "forbidden" strings are inside some files

### Current Behavior

See in "What happened"

### Possible Solution

It could be possible to replace all forbidden tokens with their escaped counterpart or remove them from the text which is getting sent to the AI

**Comment by di-sukharev** [comment]
this must be an openai or other provider constraint, can not really do anything. i think openai makes this to prevent prompt hacking
