### ISSUE TITLE
Infinite loop setting the key

### ISSUE THREAD

**Issue by jucasoliveira** [di-sukharev/opencommit#4]
- When adding the openAI token, the code show the same error message.

- My machine is a macbook pro m2 , running on Ventura 13.12.1

<img width="566" alt="Screenshot 2023-03-10 at 15 50 51" src="https://user-images.githubusercontent.com/11979969/224361754-a2969731-1f10-485b-81e6-1ab099bd8f67.png">

**Comment by fatihmert** [comment]
I solved like this;

1. Create `~/.opencommit`
2. Add your key like `.env` format to into the that file

```
OPENAI_API_KEY=sk-##################
emoji=true
```

save file after then try again set config command.

**Comment by jucasoliveira** [comment]
It solved, thanks!
