### ISSUE TITLE
[Bug]: v3.1.2 doesn't work with local ollama

### ISSUE THREAD

**Issue by ariitano** [di-sukharev/opencommit#405]
### Opencommit Version

3.1.2

### Node Version

20.6.1

### NPM Version

10.5.0

### What OS are you seeing the problem on?

Other Linux Distro

### What happened?

I upgraded to the latest version with npm installation, and my configuration (which worked perfectly with the previous version) doesn't work anymore, I'm getting asked for openAI api key while I don't use their API

### Expected Behavior

COmmit generation

### Current Behavior

An error message is generated

### Possible Solution

Please check if changes in env variables are needed.
If I downgrade to v3.0.20 it works again.

### Steps to Reproduce

npm i -g opencommit@latest
oco

### Relevant log output

```shell
◇  📝 Commit message generated
│
└  ✖ The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' }).
```

**Comment by di-sukharev** [comment]
👁️

**Comment by di-sukharev** [comment]
what is your OCO_AI_PROVIDER var set to?

**Comment by ariitano** [comment]
OCO_AI_PROVIDER='ollama/phi3.5:3.8b'

**Comment by di-sukharev** [comment]
there was a change, you should now set `OCO_AI_PROVIDER=ollama` and `OCO_MODEL=phi3.5:3.8b`

**Comment by ariitano** [comment]
THanks, I must have read the documentation better (or maybe give you time to write it :) )

**Comment by di-sukharev** [comment]
i'm updating the docs, thank you <3
