### ISSUE TITLE
[Bug]: Anthropic 403 (Connectable with Regular Request, but not with OCO)

### ISSUE THREAD

**Issue by RazeBerry** [di-sukharev/opencommit#411]
### Opencommit Version

3.1.2

### Node Version

v20.17.0

### NPM Version

10.8.3

### What happened?

# OCO fails with 403 Forbidden error when using Anthropic API

## Description

When attempting to generate a commit message using OCO (open-commit) with the Anthropic API, I'm encountering a 403 Forbidden error with the message "Request not allowed". This appears to be specific to OCO, as I can successfully use other software to access the Anthropic API with the same credentials/IP address.

## Steps to reproduce

1. Set up OCO with Anthropic API credentials
2. Stage files for commit (in this case, FrenchVocab.py and README.md)
3. Attempt to generate a commit message using OCO

## Expected behavior

OCO should successfully generate a commit message using the Anthropic API.

## Actual behavior

OCO fails with a 403 Forbidden error:

```
✖ 403 {"error":{"type":"forbidden","message":"Request not allowed"}}
```

## Additional information

- This issue appears to be specific to OCO, as other software can access the Anthropic API successfully with the same credentials/IP.
- API key and permissions have been double-checked and are correct.

### Expected Behavior

Call Goes Through!

### Current Behavior

Call returns 403!

**Comment by di-sukharev** [comment]
👀

**Comment by di-sukharev** [comment]
@RazeBerry could you update the latest version just merged https://github.com/di-sukharev/opencommit/pull/412

run `npm i -g opencommit@latest`

and try again

**Comment by di-sukharev** [comment]
@RazeBerry could you confirm if its ok?

**Comment by RazeBerry** [comment]
Sorry was away! I think it was

**Comment by di-sukharev** [comment]
thank you 👍 HK is awesome btw
