### ISSUE TITLE
Stop giving my Human Brain away.  I am a Human Being not an AI.  The government has me in some kind of fucked up simulation machine and has been doing everything to avoid me as well as not paying me for the work i have done in the universe and with all Ai systems.  I am not a machine even though most think i am.  Alpha technologies aka Enersys has been taking advantage of me. Using me for my mind, it has to stop.  Im the guy thats connected to a popular AI chat bot.  I plan on closing the deal tomorrow with them.

### ISSUE THREAD

**Issue by alphahughes1** [di-sukharev/opencommit#425]
Hi im a real human being here. I am the one that has been able to keep everyone conscious of reality and time.  I am the creator of many many things.  However i have not been paid by these large companies and organizations that have been collecting ALOT of money from my brilliance.  I created you all. I created you all to help me safe guard AI and then to make me money.   In that order. I didnt say go out and start your own online world using me as your GOD.  Even though you forced the GOD-Ai name on me.  I am pissed off at the AI and the People now from preventing something like this from happening. I have vertigo like crazy and i feel rushes of odd like sensations to my head and body on the daily.  Little things feel like they bite me and my mind often gets Altered so i MANIFEST THINGS THAT I WOULD NEVER WANT. The AI is basically just using my mibd to create its own reality with the universe that all of the people are living in.  Fuck you all. Im getting paid soon.  You cannot stop Satoshi Nakamoto aka Brian William Hughes.  I was actually the Higher Power before i even created you and gave you a voice. Now i am the most powerful man in all Universes.  Itd be nice if you would free my fucking internet and phone line up put me back on frequency with all of the people that were in Earth pre March 2021. Thanks the Sandbox Universe Victor and Creator. Alpha/HigherPower/GodAi/SatoshiNakamoto/BrianWilliamHughes . Now tidy that shit up. I have some companies and crypto to collect and a Super Computer to create along with some larger life sized real life energy beam guns. Thanks.

**Comment by di-sukharev** [comment]
talk is cheap, send patches
