### ISSUE TITLE
[Help] My oco stopped working

### ISSUE THREAD

**Issue by psjjonathan** [di-sukharev/opencommit#428]
### Opencommit Version

1.02

### Node Version

20.18.0

### NPM Version

10.9.0

### What happened?

Sunddenly my Windows 10 stopped running some variables, one of them opencommit. I tried to set manually the path to the opencommit \.bin but it doesn't  work on my VS Code, otherwise it works on my CMD.  Any idea?

When I try to run it on my VS Code I receive this message:
```
+ oco
+ ~~~
    + CategoryInfo          : ObjectNotFound: (oco:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Expected Behavior

The oco to run smoothly as always did.

### Current Behavior

Returns the message bellow:
```
+ oco
+ ~~~
    + CategoryInfo          : ObjectNotFound: (oco:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by di-sukharev** [comment]
did you try to remove opencommit with npm and reinstall it?

**Comment by psjjonathan** [comment]
I did

**Comment by psjjonathan** [comment]
I'm sorry for not closing the issue before. I just formated my pc and installed Windows again. As I said, this was not the only issue I was having, but any script I'd try to run. After I reinstall Win10 everything is in place again.

**Comment by di-sukharev** [comment]
nice, take care ;)
