### ISSUE TITLE
Possibility to change some message patterns

### ISSUE THREAD

**Issue by brunoricardosecco** [di-sukharev/opencommit#5]
I'm thinking about changing some message patterns on the lib configurations, ie removing the `* ` from the beginning of the messages. Is that doable?

**Comment by brunoricardosecco** [comment]
Actually, thinking better now, the easiest/best way of doing that is to make the message editable before confirming the commit

**Comment by di-sukharev** [comment]
@brunoricardosecco bro, try [setting the hook](https://github.com/di-sukharev/opencommit/issues/1#issuecomment-1463546118)

**Comment by cedricmay** [comment]
I would love to be able to remove the `*` as well from the commit message. 
A config to set the message pattern would be amazing!

**Comment by di-sukharev** [comment]
well, it really looks * is not needed, so i've removed it completely, update pls `npm i -g opencommit`. PRs for `message pattern` are welcome if you want it to be done quicker. If no PRs happen — i'll do it myself at some point :)

**Comment by brunoricardosecco** [comment]
Thank youu!!
