### ISSUE TITLE
Suggest adding 'Edit' option to the Yes/No confirmation

### ISSUE THREAD

**Issue by tqwhite** [di-sukharev/opencommit#53]
The tool did a great job of generating the message. I would have liked to add a note about who suggested the fix.

Also, another time, it got a huge amount right but also got something wrong. I would have liked to fix it without losing the AI contribution. (In that case, I copied the message, said No and did a conventional commit with edited text.)

**Comment by kdiogenes** [comment]
Another approach you can use is to commit and then execute a `git commit --amend`.
