### ISSUE TITLE
zsh: command not found: oc

### ISSUE THREAD

**Issue by evanmarshall-dev** [di-sukharev/opencommit#56]
Hello. I entered a repository/project. Installed opencommit (oc) globally via `yarn add global opencommit`, and when I go to assign api key or emoji to true, I receive the above error: `zsh: command not found: oc` OR `zsh: command not found: opencommit`. I am using wsl 2 on Windows 11. I am not sure if that is the problem. I went through the same process running zsh on my MacBook and it works fine.

**Comment by di-sukharev** [comment]
looks like your windows env issue, try to google pls

**Comment by CamiloBernal** [comment]
Hi, Please reopen the issue, as I am testing on Linux Manjaro 23 with zsh and encountering the same error message '`zsh: command not found: OC'`. In my case, I am using nvm and npm. Thank you very much.
