### ISSUE TITLE
Bug?: Untracked files still end up in the commit context

### ISSUE THREAD

**Issue by watzon** [di-sukharev/opencommit#62]
Don't know if this is intended or not, or if there is a config flag to disable the behavior. It seems as though making a commit in which there are some untracked files, still references the untracked files.

To reproduce:
- Make some changes to a file
- Add a file, but don't add it to git
- Run `git commit` to activate the hook

In my case it generated a commit message that mentioned the untracked files, as well as the one file that was tracked and had changes.

**Comment by matt-degraffenreid** [comment]
This was just addressed in #48. Waiting for a reviewer to merge into dev
