### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by smartycoder** [di-sukharev/opencommit#7]
Generating the commit message
│
└  ✖ Error: Request failed with status code 429

**Comment by di-sukharev** [comment]
`Error Code 429 - Rate limit reached for requests`

hehe, looks like you reached api limit

https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests

**Comment by smartycoder** [comment]
> `Error Code 429 - Rate limit reached for requests`
> 
> hehe, looks like you reached api limit
> 
> https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests

hehe, I should google it first

**Comment by giuliozelante** [comment]
I just put my payment method and limits but I still get that error

**Comment by giuliozelante** [comment]
> I just put my payment method and limits but I still get that error

never mind, I just had to generate another api key
