### ISSUE TITLE
Error when commits are done

### ISSUE THREAD

**Issue by M8-Babbage** [di-sukharev/opencommit#72]
Howdy, thank you very much for this amazing tool.

I am using it, but I encountered an error when the commit finished, here is the error.

![image](https://user-images.githubusercontent.com/119270803/228275325-a00384fa-07b7-49ed-831f-9fff32ff40ae.png)

**Comment by di-sukharev** [comment]
try updating `npm i -g opencommit@latest`

**Comment by M8-Babbage** [comment]
![image](https://user-images.githubusercontent.com/119270803/228542586-6bfda513-0caf-46c8-8aa7-42f8f81f199f.png)

**Comment by M8-Babbage** [comment]
![image](https://user-images.githubusercontent.com/119270803/228542686-109b03c4-c26a-4ac3-a8d7-14a22d094381.png)

**Comment by di-sukharev** [comment]
should be fixed now, update pls `npm i -g opencommit@latest`

**Comment by M8-Babbage** [comment]
![image](https://user-images.githubusercontent.com/119270803/228892145-0898fbdb-0dc8-40ef-9a85-c076a3b73916.png)
